### ISSUE TITLE
Back-end: Fix position logic for cards in a choice

### ISSUE THREAD

**Issue by SjoenH** [equinor/MAD-VSM-WEB#254]
Cards might get the same position number. Thus those cards cannot be re-arranged.
![image](https://user-images.githubusercontent.com/3164065/138236774-0798da3c-4e56-43fc-a6b2-5de540525033.png)

**Testing:** see comment https://github.com/equinor/MAD-VSM-WEB/issues/254#issuecomment-970111206
**Please test overall position and re-ordering of cards in the canvas**

**Comment by SjoenH** [comment]
@Magos will take a look at implementing positioning logic without any changes needed for the front-end.

Note: position is not used in the front-end.

**Comment by SjoenH** [comment]
@SjoenH Do some initial testing. Thank you future me.

**Comment by SjoenH** [comment]
Initial testing in dev done. We have migrated the changes to test-environment for testing @ntorsen.
A bit hard to check for this... 
The problem was that Sometimes a card under a choice wouldn't move when you tried to re-order the children.
This shouldn't happen any more.

**Please test overall position and re-ordering of cards in the canvas**

**Comment by ntorsen** [comment]
@SjoenH working really well 🙌
Even got this message when trying to move a parent to a child-object:
![image](https://user-images.githubusercontent.com/89014017/141987430-a104b44c-4dce-476c-b5ed-78a465142c5e.png)

**Comment by SjoenH** [comment]
@Magos let's talk about releasing this bug-fix.

**Comment by SjoenH** [comment]
**Planning a release for this today.**
First to QA as a test-run, then we will add a service-message and get it out into prod.

**Comment by SjoenH** [comment]
Release to QA went OK. Verified by Magnus and me.
Service message is put up in Production.

**Planning API-release around 11:00. There will be some downtime estimated to around 15 minutes.**

**Comment by SjoenH** [comment]
We have discovered a bug that is affecting adding and reordering cards in a process. We are investigating and considering our options.

**Comment by SjoenH** [comment]
Rolling back seems to work OK for QA. As long as no-users have started using the new position as introduced in the new api.

It seems like I'm the only one that has done any changes in this period, so we should be fine, but we will keep our eyes open.

**Comment by SjoenH** [comment]
API was rolled back successfully. We did verify that all cards are using the old positioning index. 🙆‍♂️

**Comment by SjoenH** [comment]
@ntorsen Ready again in test.
From initial testing, this looks good. But we will need to do take our time, testing the overall position and re-ordering of cards in the canvas.

**Comment by ntorsen** [comment]
Created a new process and added a main-activity to it. Then added a card under it. Does not give childIndex -1 anymore. First card added under main-activity gets number 1289, and the following cards get 1290 and 1291. 

![image](https://user-images.githubusercontent.com/89014017/142602023-e72ab157-186f-42fe-a5fa-900614319587.png)

When moving position of a card, for example if I move the first sub-activity card to another main-activity, childIndex number change. In this case it first said 1289 and when moving it to another main-activity its then 1290. Don't know it this is important or not..

I don't get any negative numbers for childIndex when adding card under main-activity (that is for both sub-activity, choice, and waiting card).

Other remarks: 
- Still get message for not being able to move a parent to a child-object. So that's good 👍 
![image](https://user-images.githubusercontent.com/89014017/142602576-5a617d4e-1131-4343-a650-3b73ef443aae.png)

- Did an overall testing with moving different cards around, and it is working well. I get no errors or weird behavior when moving cards.



Possible flaw:
- If I delete a row of cards that contained QIPR, they still appear in category-page. And I am still able to work on the page by adding/renaming/deleting categories
![image](https://user-images.githubusercontent.com/89014017/142602999-22a5873a-a289-46dc-9b6d-1dcf7de64b7a.png)

![image](https://user-images.githubusercontent.com/89014017/142603054-4fc0201d-3233-4927-ad7e-9a998d1d8179.png)

@SjoenH

**Comment by Magos** [comment]
I would say that keeping the QIPRs around even if the cards they're on is deleted is intended as far as I understand.

**Comment by SjoenH** [comment]
Thanks for testing @ntorsen.

**Let's wait till next week with releasing this fix.** 
I want to be on the cautious side for this release. 
Let's have a talk on Monday on when would be a good release window.

-----
>     * Still get message for not being able to move a parent to a child-object. So that's good 👍
>       ![image](https://user-images.githubusercontent.com/89014017/142602576-5a617d4e-1131-4343-a650-3b73ef443aae.png)
Good! BTW. this check is done in the front-end. Not sure if we would throw an error in the API for it. @Magos When you have time, it would be good to verify what API allows here. But low priority, atm.

-----
>     * Did an overall testing with moving different cards around, and it is working well. I get no errors or weird behavior when moving cards.
> 
> 
> Possible flaw:
> 
>     * If I delete a row of cards that contained QIPR, they still appear in category-page. And I am still able to work on the page by adding/renaming/deleting categories

This is, as @Magos says, working as intended.
**PQIRs exists by itself** and can be added to as many cards in a process you want.  _(Though I see how the design makes it look like there is a stronger link here...)_
**Categories also exists for themselves** and can be added to as many PQIRs as you want.
